# Generated by Django 6.0.2 on 2026-02-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmodel',
            name='title',
        ),
    ]
